# trace application exceptions
aelns:
    exception:
        trace: false

# logback spring config
log:
    path: /logs
    level: DEBUG

# logging config
logging:
    level:
        com:
          aelns: DEBUG

# trace application
trace: false

# spring
spring:
    profiles:
        active: dev
    output:
        ansi:
            enabled: ALWAYS
    mvc:
        date-format: yyyy-MM-dd HH:mm:ss
        dispatch-trace-request: true
        dispatch-options-request: true
        throw-exception-if-no-handler-found: true
        static-path-pattern: /static
    freemarker:
        check-template-location: false
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/dev?characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        tomcat:
              max-active: 500
              test-on-borrow: false
              maxWait: 4000
              jmx-enabled: false
              test-while-idle: true
              test-on-return: false
              validation-interval: 30000
              validation-query: SELECT 1
              time-between-eviction-runs-millis: 30000
              initial-size: 5
              min-evictable-idle-time-millis: 30000
              max-idle: 100
              min-idle: 50
              log-abandoned: false
              remove-abandoned: true
              remove-abandoned-timeout: 180
              jdbc-interceptors: org.apache.tomcat.jdbc.pool.interceptor.ConnectionState;org.apache.tomcat.jdbc.pool.interceptor.StatementFinalizer

# MyBatis
mybatis:
  type-aliases-package: com.aelns.**.model
  mapper-locations: classpath*:/com/aelns/**/dao/mapper/*Mapper.xml
  check-config-location: true
  config-location: classpath:mybatis-config.xml






